# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: myPage | John
email: jhnl.biz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a collection of projects I have worked on and ideas that I will explore 
github_username: jhnliu
minimal_mistakes_skin: dark
search: false


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "John Liu"
  avatar : "/assets/images/propic.jpg"
  bio    : "Strategic thinking | Data Analytics | Think out of the box"
  location: "Sydney, AU"
  
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jhnl/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jhnliu/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jhnl/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jhnliu/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      teaser: /assets/images/yosemite.JPG

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      read_time: true
      author_profile: true
      teaser: /assets/images/yosemite.JPG


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
